name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    env:
      DJANGO_SECRET_KEY: "supersecret"
    steps:
    - uses: actions/checkout@v3
    - name: Create requirements.txt from rye lockfile
      run: sed '/-e file/d' requirements-dev.lock > requirements.txt
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd src/triangle_api && python manage.py test
